/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TbilisiRouteImport } from './routes/tbilisi'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as IndexRouteImport } from './routes/index'

const TbilisiRoute = TbilisiRouteImport.update({
  id: '/tbilisi',
  path: '/tbilisi',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/embed': typeof EmbedRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tbilisi': typeof TbilisiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/embed': typeof EmbedRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tbilisi': typeof TbilisiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/embed': typeof EmbedRoute
  '/guide': typeof GuideRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tbilisi': typeof TbilisiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/admin'
    | '/embed'
    | '/guide'
    | '/login'
    | '/map'
    | '/sitemap.xml'
    | '/tbilisi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/admin'
    | '/embed'
    | '/guide'
    | '/login'
    | '/map'
    | '/sitemap.xml'
    | '/tbilisi'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/admin'
    | '/embed'
    | '/guide'
    | '/login'
    | '/map'
    | '/sitemap.xml'
    | '/tbilisi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AdminRoute: typeof AdminRoute
  EmbedRoute: typeof EmbedRoute
  GuideRoute: typeof GuideRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TbilisiRoute: typeof TbilisiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tbilisi': {
      id: '/tbilisi'
      path: '/tbilisi'
      fullPath: '/tbilisi'
      preLoaderRoute: typeof TbilisiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AdminRoute: AdminRoute,
  EmbedRoute: EmbedRoute,
  GuideRoute: GuideRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TbilisiRoute: TbilisiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
